### ISSUE TITLE
X windows are created with 1px border on Gentoo

### ISSUE THREAD

**Issue by carbohydratesn** [ch11ng/exwm#169]
Using Arc h, everything works great - but on Gentoo, a small 1px border is created around all X windows on the 'outer' (left, right, top) sides of the screen.   Emacs picks this area up as part of the main emacs window.  They can be manually moved or resized to fit the space, but this is difficult.  Any frames that aren't fullscreen have this border.

Using Gentoo GNU/Linux, xf86-video-modesetting driver, Emacs 24.5, not sure what else might be relevant...

**Comment by ch11ng** [comment]
Did you mean floating X windows?  If so the border width is controlled by `exwm-floating-border-width` and default to 1 pixel, but it should be visible on Arch too.  Otherwise please provide a screenshot to illustrate what it is.

**Comment by carbohydratesn** [comment]
No, it's a problem with 'regular' X windows.  It's hard to get a good screenshot of this, but I did -





Note the dark border.   The X window should extend to the edges of the screen - it doesn't here, that border is emacs.  It makes it impossible to, for example, click on browser tabs with the mouse up against the top of the screen.  You have to move it down a pixel to actually hit the window.  

![Normal](https://cloud.githubusercontent.com/assets/8284150/16714696/524313c8-4688-11e6-8fdb-38033efe730e.png)

Windows are flush with each other in the center of the screen - emacs  doesn't 'peek through' between X windows.  Just between X windows and the edges of the screen.

In fullscreen, X windows do extend all the way to the edges of the screen, and behave as expected.

![Fullscreen](https://cloud.githubusercontent.com/assets/8284150/16714698/5dffdfb6-4688-11e6-933d-a6dd0b2f5671.png)

**Comment by carbohydratesn** [comment]
Here are the same screenshots duplicated in Arch.  No border, the X window is flush with the edges of the screen

![Normal window](https://cloud.githubusercontent.com/assets/8284150/16714774/eb467f72-468a-11e6-833f-f3e1704ccb1e.png)


![Fullscreen window](https://cloud.githubusercontent.com/assets/8284150/16714777/f4f650f6-468a-11e6-80ae-4b245d1de31a.png)

**Comment by ch11ng** [comment]
I can't tell from the screenshots what the black borders are.  Maybe they're the external or internal border of the Emacs frame.  You may check them with `(frame-parameter nil 'border-width)` and `(frame-parameter nil 'internal-border-width)` which should normally yield `0`.  They're probably not fringes/margins though as those are automatically disabled in `exwm-mode`, but you might also check them.

OTOH the Emacs frame itself may not get resized correctly.  You may check this by running `xwininfo` and picking an empty workspace.

**Comment by carbohydratesn** [comment]
Fantastic, that's it - thanks for the wisdom!

internal-border-width is 0 on Arch, and 1 on Gentoo.  Launching emacs with '-ib 0' makes it good :)

**Comment by ch11ng** [comment]
This is fixed in 0863f4149062089abdadd0dd795ad17d0e73da03.  The command line switch is not required any more.

**Comment by carbohydratesn** [comment]
Hm...at first, I was able to upgrade and this patch worked.  But the update stopped my custom 'exwm-toggle-input-mode' function from working, so I rolled back and continued using '-ib 0' when executing emacs.

Now, trying to update EXWM, this patch _isn't_ working, I'm still getting a border after starting emacs.  

If I navigate to exwm-workspace.el and execute the new

`(let ((f...
...internal-border-width . 0)))))))`

chunk of code manually, the borders are removed.  But otherwise, they're still there :(

I'm going to try strengthening my git-fu and testing different patches - it could've been anything in those 12 days.  Hopefully I can narrow it down.

**Comment by carbohydratesn** [comment]
Okay, commit 0863f4149062089abdadd0dd795ad17d0e73da03 does not actually seem to fix the issue, and brings up a few others - none of my hotkeys work.  Calling EXWM functions with M-x does work, but nothing set with exwm-input-set-key does.  

Using xelb commit bb8f19a0f8d0c4168c077280e8a0db294ae0b864 for compatibility

The parenthesis rebalance in 1a716d39397edfc2a083c479817ea7d40b23fd54 fixes that problem, and hotkeys work again, but I'm still getting an internal border.


Some of this could be due to the config I'm using, notably calling xrandr - I saw that there were other issues with xrandr and recent commits

https://github.com/CestDiego/spacemacs/blob/SpacemacsOS/layers/%2Bwindow-management/exwm/packages.el

`   (require 'exwm-randr)
    (setq exwm-randr-workspace-output-plist '(0 "VGA1"))
    (exwm-randr-enable)`

With everything up-to-date, all is well except for the internal border remaining.

**Comment by ch11ng** [comment]
Please make sure everything is update-to-date.

Does the `-ib 0` argument still work? If so `(set-frame-parameter nil 'internal-border-width 0)` should also work (for the current workspace), does it? And considering EXWM now has dynamic workspace support, does the issue affect all workspaces or only newly-created ones?

**Comment by ch11ng** [comment]
Any update? I've just fixed a related problem, but not sure if it's the same.

**Comment by ch11ng** [comment]
Are you still experiencing the issues? Or are there any Gentoo users around here?

**Comment by ch11ng** [comment]
I tried Gentoo's official LiveDVD (20160704) today and cannot reproduce this issue with various configurations.  So I assume the issue is not system-dependent. I noticed you activated quite a lot of packages; please try the default configuration of EXWM and see if the issue was actually caused by some package.  I'm closing this issue for now.  Please reopen it if you can confirm it's caused by EXWM.
