### ISSUE TITLE
minibuffer-setup-hook vs window-size-change-functions

### ISSUE THREAD

**Issue by pipcet** [ch11ng/exwm#40]
Running

    (progn
      (message (make-string 3000 ?*))
      (start-process "xterm" nil "xterm"))

produces a small problem: the minibuffer gets resized without our noticing. The problem is that `minibuffer-setup-hook` doesn't really say anything about the minibuffer being resized, just about its being entered.

I think this is also the problem in the screenshot at #27.

There are two alternatives: `window-size-change-functions` is precisely what we want, but it's only called when there is a menu bar. `window-text-change-functions` is called whenever anything might have changed, which is very often, so it might lead to noticeable slowdown.

There's also `echo-area-clear-hook`, but that's not called when the echo area grows, just when it shrinks.

I think the best way forward is to fix the xdisp.c code to call `window-size-change-functions` even when there is no menu bar, and submit that to upstream Emacs. Until it's fixed, things aren't all that horrible, but slightly annoying.

Or do you have a better idea?

**Comment by pipcet** [comment]
Sorry, I must have gotten confused between `prepare_menu_bars` and `update_menu_bar`. `window-size-change-functions` is what we want.

**Comment by ch11ng** [comment]
> Running
>
> ```
(progn
  (message (make-string 3000 ?*))
  (start-process "xterm" nil "xterm"))
```
> produces a small problem: the minibuffer gets resized without our noticing. The problem is that `minibuffer-setup-hook` doesn't really say anything about the minibuffer being resized, just about its being entered.

Rather than *minibuffer*, I think it's *echo area*. They are different things. `minibuffer-setup-hook` certainly has nothing to do with it.

> There are two alternatives: `window-size-change-functions` is precisely what we want, but it's only called when there is a menu bar.
> ...
> I think the best way forward is to fix the xdisp.c code to call `window-size-change-functions` even when there is no menu bar, and submit that to upstream Emacs.

I haven't checked the C source yet, but what's the reason for such inconsistent behaviors? If it's a result of carelessness, it should be fixed of course.

> Or do you have a better idea?

We originally only do refresh in `window-configuration-change-hook`; `minibuffer-setup-hook` was added later to account for minibuffer resize. Now we want to add a third. It's better to do refresh just in one place if possible.

**Comment by pipcet** [comment]
Again, I was wrong about `window-size-change-functions`; it's run when there is no menu bar, but there still appear to be cases when it isn't run even though the window sizes do change.

You're right, of course, about the difference between minibuffer and echo area.

I'll be experimenting more to see which combination of hooks is sufficient and minimal; I suspect it might be `window-size-change-functions` and `focus-in-hook`, the latter to catch when the echo area is resized to a single line because a different frame is focused. Hopefully we can then avoid using the `window-configuration-change-hook` and `minibuffer-setup-hook` and, in particular, `window-text-change-functions`, which is called very often.

**Comment by pipcet** [comment]
I've reported this as an Emacs bug at http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21333 , so we can hopefully use `window-size-change-functions` (and that hook only) for future Emacs versions. If we want to work around the issue in older versions, we can use `advice-add` as in 
https://github.com/pipcet/exwm/commit/71112b33937a99d67080b4ca5f4ef121a7dec851 .

**Comment by ch11ng** [comment]
Great. But this workaround should not be included until this minor bug is fixed upstream, so that we can decide if it's necessary.

**Comment by pipcet** [comment]
As I feared, there's no consensus to fix `window-size-change-functions`, but on newer Emacs versions (after 2013-10-29), there's another alternative: `pre-redisplay-function`. I understand we probably want to support old Emacs versions that don't have that, though.

I thought we'd be able to save some code, but once I added all the special cases back in, it's a matter of replacing 59 lines of code with 59 other lines of code: https://github.com/ch11ng/exwm/compare/master...pipcet:pre-redisplay-function . So nothing to be gained there except for some possible code cleanup.

**Comment by ch11ng** [comment]
It seems `pre-redisplay-function` was introduced in Emacs 24.4 and later changed to `pre-redisplay-functions` in 25.1. Since this issue is not serious (only annoying when lots of message is dumped), we can simply leave it unfixed for earlier version of Emacs.

**Comment by pipcet** [comment]
25.1 has both `pre-redisplay-function` and `pre-redisplay-functions`. You're right that the issue isn't that serious, so we should be fine checking whether it's bound and installing ourselves if it is. Will prepare a PR (just close it if you're not okay with the way I've rewritten the layout refresh code).

Some users might like the old behavior better (because X window resizes can be slow and disruptive), so I'll write something on the Wiki about setting `resize-mini-windows` to nil to achieve that, assuming your okay.

**Comment by ch11ng** [comment]
> 25.1 has both `pre-redisplay-function` and `pre-redisplay-functions`

But we should prefer the latter.

> Some users might like the old behavior better (because X window resizes can be slow and disruptive), so I'll write something on the Wiki about setting `resize-mini-windows` to nil to achieve that, assuming your okay.

Good idea. A better solution is to put an intermediate layer (as the direct parent of the X window) and resize that instead; it won't be disturbing then. But that's too much work indeed.

**Comment by pipcet** [comment]
`pre-redisplay-functions` doesn't work for our purposes, unfortunately. In the common case of the minibuffer being resized in the middle of a redisplay, the handler is never called for some windows. I'm not certain yet whether that is a bug or intended behavior.

I think the intermediate layer idea is excellent, but belongs into a separate "this application is broken, don't actually resize it until N seconds have passed" library, just like the preload library I'm using to use xterm in line mode.

**Comment by ch11ng** [comment]
Fixed in 0e4055d3392537cd4138181b9c615fa03053add8.  There're actually two methods now.
