### ISSUE TITLE
Mode where nothing is sent to xwindow

### ISSUE THREAD

**Issue by jtamagnan** [ch11ng/exwm#83]
Would it be possible to have a mode where no input is sent to the xwindow. This would be useful for packages like ace-window. Ace-window is used to switch windows in a better way (I think) than 'other-window (C-x o). After running ace-window you press a key and it will set emac's focus to be whichever window is designated by that key. I have ace-window bound to C-x p. After pressing C-x p ace-window waits for a key press (?a ?s ?d ?f ?g ?h ?j ?k ?l) and will change to whichever window is associated to that key. The issue is that after pressing C-x p when in exwm-mode the next character I press gets eaten by the xwindow.
Would it be possible to have that following key press not be eaten?

**Comment by marcushg** [comment]
Now that's a good timing since we're discussing something similar on a PR from (spacemacs)[https://github.com/syl20bnr/spacemacs/pull/3321]. We would like to be able to configure exwm so that it wont send **any** keys to the X-window itself and essentially makes exwm behave like vim/spacemacs modes (input vs normal mode).

**Comment by ch11ng** [comment]
As far as ace-window is concerned, I can think of two straightforward solutions:
1. Providing a global flag, set/unset before/after calling `ace-window`
2. Providing a global white list including commands like `ace-window`

OTOH, I have no idea of spacemacs, neither do I know the workflow. So I have a few questions for you, @marcushg:
+ It seems spacemacs uses <kbd>SPC</kbd> as a prefix key. So would it be enough to just add this key (and perhaps other extra prefix keys, if any) to `exwm-input-prefix-keys`? If not, what would other keys be used for? I don't believe all keys are used in spacemacs.
+ How should the `char-mode` behave in spacemacs?

Anyway, I think the issues with ace-window and spacemacs should be resolved as a whole. I personally prefer the second one though it may not work for spacemacs, since the first might be problematic when the flag is modified from various places.

**Comment by marcushg** [comment]
I am simplifying a bit and only talk about spacemacs default vim editing mode right now (see below):
Someone more knowledgeable on spacemacs pls correct me if I am mistaken!

@ch11ng First of all, thanks for your help in that regard. Spacemacs makes heavy use of `evil-mode` which essentially adds vim behaviour to emacs, which you're probably familiar with. The relevant part of evil is the distinction between input and normal mode which roughly translates to your two modes, line (==normal) and char (==input) mode.
Now, the difference between the behaviour of normal mode and line mode is that unless you press one of the `exwm-*-prefix-keys` the key sequences will be forwarded to the X-window (I am talking about the `or` conditions in [exwm-input.el](https://github.com/ch11ng/exwm/blob/master/exwm-input.el#L281)).

If possible, it would be nice if we could make it configurable that **no** key sequences are forwarded to the X-window in line mode, for instance by having a global flag and add it to the aforementioned OR conditions, so that all keys go to Emacs itself. I can't think of an elegant solution right now, but I believe this would also help @jtamagnan. Your idea with adding `SPC` to `exwm-input-prefix-keys` would probably work in my case as well - except it could be tedious (but doable) if more keys would be involved.

The thing get's more complicated with the different [editing styles](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#editing-styles) defined by spacemacs, but I understand that this is not something exwm should be concerned with.

**Comment by ch11ng** [comment]
Thank you for the explanation, @marcushg. So it seems a brain-dead solution such as providing a global flag will not work if the editing styles of spacemacs are concerned.

I've just gone through the documentation of spacemacs, and I think it only includes a few prefix keys like <kbd>SPC</kbd>, <kbd>C-m</kbd>, etc. As for keys in 'normal mode' such as <kbd>h</kbd>, <kbd>j</kbd>, <kbd>k</kbd> and <kbd>l</kbd>, I don't know what they can be used for in an `exwm-mode` buffer (perhaps mapped to arrow keys). Did I miss something?

**Comment by marcushg** [comment]
I don't think you missed anything - but spacemacs got really big lately, so I am not 100% sure.

It looks like adding `SPC`, etc. to the `exwm-input-prefix-keys` will be the saner solution for spacemacs, although that unfortunately does not help @jtamagnan. I will suggest it in the issue over at the spacemacs repo....

**Comment by jtamagnan** [comment]
I originally liked the idea of having a flag that can be turned on and off before and after a function but like you said that might get messy if the the flags aren't turned off. It would also require wrapping the functions which might be messier than some people want. The whitelist of commands seems like a really cool solution.

Theres also another issue with ace-window. Where if I am in an x-window in line mode, and I run 'other-window and I then run 'ace-window it won't switch to a buffer in another frame properly. It will flash to the window I seleced and then immediatly jump back to the window that I was just in. The only way to fix this is to move my cursor to a different workspace than the original one. The workspace that I move my cursor to does not need to be the same one that I am trying to move to with ace-window.

Also there seems to be an issue where if I click on a window that is on another workspace the first input that I do in that window does nothing. This issue does not exist if I use ace-window to go that window or if the window that I clicked on is in the same workspace.

**Comment by ch11ng** [comment]
Hi @jtamagnan,

It seems that you have a multi-monitor setting.  I believe the other two issues you reported have something to do with #39/#45.  I'm still investigating it and hopefully the issues you encountered will be fixed once I find a solution to the old one.

**Comment by jtamagnan** [comment]
Oh cool! I hadn't realized that those were related! My bad!

**Comment by ch11ng** [comment]
The following code should work now.

``` elisp
(push 'ace-window exwm-input-command-whitelist)
```

**Comment by ch11ng** [comment]
Just FYI, since 0e4055d3392537cd4138181b9c615fa03053add8 the workaround I provided above is no longer needed.  The problem is fully resolved now.

**Comment by jtamagnan** [comment]
Very cool! Thanks for the heads up!

**Comment by Stebalien** [comment]
While the immediate `ace-window` problem was addressed, it would still be nice to get a mode where nothing (except those keys listed in `exwm-input-set-simulation-keys`) is sent to the X window. My specific use case is implementing a "normal" mode (like vim/evil). In "normal" mode, I'd pass through standard navigation keys (e.g., `h`, `j`, `k`, `l` as arrow keys) for all applications and map other keys on an application by application basis (I don't really use many GUI apps). "insert" mode would be char-mode (with a key to escape back to "normal" mode).

**Comment by ch11ng** [comment]
@Stebalien If you don't need to capture "every" key then the snippet below might give you some ideas.  Note the range 1 ~ 127 covers nearly all keys on an English keyboard.

```elisp
(add-hook 'exwm-manage-finish-hook
          (lambda ()
            (when (and exwm-class-name
                       (string= exwm-class-name "Firefox"))
              (setq-local exwm-input-prefix-keys (number-sequence 1 127)))))
```

**Comment by Stebalien** [comment]
That should work but what about exposing `exwm-input--line-mode-passthrough` as 
`exwm-input-line-mode-passthrough`? (I can submit a PR).

**Comment by ch11ng** [comment]
@Stebalien You can use this private interface for now.  If it really proves useful we will make it public.

**Comment by Stebalien** [comment]
To be usable, `exwm-input-send-next-key` needs to set it with `let`, not `setq`:

```rust
@@ -629,16 +629,15 @@ This value should always be overwritten.")
   (let (key keys)
     (dotimes (i times)
       ;; Skip events not from keyboard
-      (setq exwm-input--line-mode-passthrough t)
-      (catch 'break
-        (while t
-          (setq key (read-key (format "Send key: %s (%d/%d)"
-                                      (key-description keys)
-                                      (1+ i) times)))
-          (when (and (listp key) (eq (car key) t))
-            (setq key (cdr key)))
-          (unless (listp key) (throw 'break nil))))
-      (setq exwm-input--line-mode-passthrough nil)
+      (let ((exwm-input--line-mode-passthrough t))
+        (catch 'break
+          (while t
+            (setq key (read-key (format "Send key: %s (%d/%d)"
+                                        (key-description keys)
+                                        (1+ i) times)))
+            (when (and (listp key) (eq (car key) t))
+              (setq key (cdr key)))
+            (unless (listp key) (throw 'break nil)))))
       (setq keys (vconcat keys (vector key)))
       (exwm-input--fake-key key))))
 
```

**Comment by ch11ng** [comment]
@Stebalien That sounds good.  Please make a PR and I'll pull it.

**Comment by ch11ng** [comment]
@yisraeldov Have you had `M-o` added to `exwm-input-prefix-keys`?

**Comment by yisraeldov** [comment]
Yes, I figured it out, thanks
